# GET tutti i prodotti
GET http://localhost:3000/api/products
###

# GET prodotto per id
GET http://localhost:3000/api/products/1
###

##Filtro prodotti
GET http://localhost:3000/api/products/filter?rating=4
###

#INSErT into cart
POST http://localhost:3000/api/insertCart
Content-Type: application/json

{
    "user_id": 2,
    "product_id": 1,
    "quantity": 1
}
###

#GET cart
GET http://localhost:3000/api/cart/2
###

#UPDATE cart
POST http://localhost:3000/api/updateCart
Content-Type: application/json

{
    "user_id": 2,
    "product_id": 1,
    "quantity": 4
}
###

#DELETE from cart
DELETE http://localhost:3000/api/deleteCart/2
###
